# Generated by Django 4.2.2 on 2023-07-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='broadband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('hoder_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('ammunt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='creditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ammount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cylenderbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.CharField(max_length=100)),
                ('consumer_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='educationfees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('your_class', models.IntegerField()),
                ('year', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_holder', models.CharField(max_length=100)),
                ('bill_id', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100)),
                ('loan_holder', models.CharField(max_length=100)),
                ('loan_number', models.CharField(max_length=100)),
                ('mob_number', models.CharField(max_length=100)),
                ('ammount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='recharge1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_name', models.CharField(max_length=200)),
                ('amout', models.CharField(max_length=150)),
                ('data', models.CharField(max_length=200)),
                ('validity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('contect', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('imgs', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='rentpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_about', models.CharField(max_length=100)),
                ('account_holder', models.CharField(max_length=100)),
                ('aount_number', models.CharField(max_length=100)),
                ('mob_number', models.CharField(max_length=100)),
                ('ammount', models.IntegerField()),
            ],
        ),
    ]
