# Generated by Django 4.2.2 on 2023-07-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register1',
            old_name='email',
            new_name='mail',
        ),
    ]
