# Generated by Django 4.2.2 on 2023-07-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_email_register1_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register1',
            old_name='mail',
            new_name='email',
        ),
    ]
